//! Nix generation — converts NodeIdentity to JSON and generates a flake.nix.
//!
//! The generated flake lives at `~/.config/kindling/generated/` and imports
//! the appropriate profile from kindling-profiles, setting `kindling.nodeIdentity`
//! from the serialized node.json.

use anyhow::{Context, Result};
use std::path::{Path, PathBuf};

use super::NodeIdentity;

/// Directory where generated Nix files are written.
pub fn generated_dir() -> PathBuf {
    dirs::config_dir()
        .unwrap_or_else(|| PathBuf::from("~/.config"))
        .join("kindling")
        .join("generated")
}

/// Write node.json (JSON serialization of NodeIdentity for Nix consumption).
pub fn write_node_json(identity: &NodeIdentity, dir: &Path) -> Result<PathBuf> {
    std::fs::create_dir_all(dir)
        .with_context(|| format!("failed to create generated directory {}", dir.display()))?;

    let json_path = dir.join("node.json");
    let json = identity.to_json()?;
    std::fs::write(&json_path, &json)
        .with_context(|| format!("failed to write {}", json_path.display()))?;

    Ok(json_path)
}

/// Generate flake.nix from the node identity.
///
/// The generated flake imports kindling-profiles and sets `kindling.nodeIdentity`
/// from node.json. The profile determines which system type (darwin/nixos) to use.
pub fn write_flake_nix(identity: &NodeIdentity, dir: &Path) -> Result<PathBuf> {
    std::fs::create_dir_all(dir)
        .with_context(|| format!("failed to create generated directory {}", dir.display()))?;

    let flake_path = dir.join("flake.nix");
    let content = generate_flake_content(identity);
    std::fs::write(&flake_path, &content)
        .with_context(|| format!("failed to write {}", flake_path.display()))?;

    Ok(flake_path)
}

/// Generate the full Nix files (node.json + flake.nix).
pub fn generate(identity: &NodeIdentity) -> Result<PathBuf> {
    let dir = generated_dir();
    write_node_json(identity, &dir)?;
    write_flake_nix(identity, &dir)?;
    Ok(dir)
}

fn is_darwin_profile(profile: &str) -> bool {
    matches!(profile, "macos-developer")
}

fn generate_flake_content(identity: &NodeIdentity) -> String {
    let is_darwin = is_darwin_profile(&identity.profile);

    if is_darwin {
        generate_darwin_flake(identity)
    } else {
        generate_nixos_flake(identity)
    }
}

fn generate_darwin_flake(identity: &NodeIdentity) -> String {
    format!(
        r#"# Generated by kindling — do not edit manually.
# Source: ~/.config/kindling/node.yaml
# Regenerate: kindling apply
{{
  description = "kindling-managed system configuration for {hostname}";

  inputs = {{
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-25.11";
    nix-darwin = {{
      url = "github:LnL7/nix-darwin";
      inputs.nixpkgs.follows = "nixpkgs";
    }};
    home-manager = {{
      url = "github:nix-community/home-manager";
      inputs.nixpkgs.follows = "nixpkgs";
    }};
    kindling-profiles = {{
      url = "github:pleme-io/kindling-profiles";
      inputs.nixpkgs.follows = "nixpkgs";
    }};
  }};

  outputs = {{
    self,
    nixpkgs,
    nix-darwin,
    home-manager,
    kindling-profiles,
    ...
  }}: let
    ni = builtins.fromJSON (builtins.readFile ./node.json);
  in {{
    darwinConfigurations.${{ni.hostname}} = nix-darwin.lib.darwinSystem {{
      system = "aarch64-darwin";
      modules = [
        kindling-profiles.darwinModules.default
        (import "${{kindling-profiles}}/profiles/{profile}")
        home-manager.darwinModules.home-manager
        {{
          kindling.nodeIdentity = ni;
          networking.hostName = ni.hostname;
        }}
      ];
    }};
  }};
}}
"#,
        hostname = identity.hostname,
        profile = identity.profile,
    )
}

fn generate_nixos_flake(identity: &NodeIdentity) -> String {
    format!(
        r#"# Generated by kindling — do not edit manually.
# Source: ~/.config/kindling/node.yaml
# Regenerate: kindling apply
{{
  description = "kindling-managed system configuration for {hostname}";

  inputs = {{
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-25.11";
    home-manager = {{
      url = "github:nix-community/home-manager";
      inputs.nixpkgs.follows = "nixpkgs";
    }};
    kindling-profiles = {{
      url = "github:pleme-io/kindling-profiles";
      inputs.nixpkgs.follows = "nixpkgs";
    }};
    sops-nix = {{
      url = "github:Mic92/sops-nix";
      inputs.nixpkgs.follows = "nixpkgs";
    }};
  }};

  outputs = {{
    self,
    nixpkgs,
    home-manager,
    kindling-profiles,
    sops-nix,
    ...
  }}: let
    ni = builtins.fromJSON (builtins.readFile ./node.json);
  in {{
    nixosConfigurations.${{ni.hostname}} = nixpkgs.lib.nixosSystem {{
      system = "x86_64-linux";
      modules = [
        kindling-profiles.nixosModules.default
        (import "${{kindling-profiles}}/profiles/{profile}")
        home-manager.nixosModules.home-manager
        sops-nix.nixosModules.sops
        {{
          kindling.nodeIdentity = ni;
          networking.hostName = ni.hostname;
        }}
      ];
    }};
  }};
}}
"#,
        hostname = identity.hostname,
        profile = identity.profile,
    )
}
